name: Deploy to EduCoder

on:
  workflow_run:
    workflows: ["Linux x64 Compiler"]
    types:
      - completed
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EduCoder_USER: ${{ secrets.EduCoder_USER }}
      EduCoder_PASS: ${{ secrets.EduCoder_PASS }}
      EduCoder_REPO: ${{ secrets.EduCoder_REPO }}
    steps:
    # 步骤1：克隆私有仓库（使用Secrets）
    - name: Clone private repository
      run: |
        git clone https://${EduCoder_USER}:${EduCoder_PASS}@${EduCoder_REPO}.git EduCoder
        cd EduCoder
    # 步骤2：获取编译产物
    - name: Get build artifacts
      run: |
        mkdir -p EduCoder/build
        cp -r ../build/* EduCoder/bin/
    # 步骤3：push到EduCoder
    - name: Push to EduCoder
      run: |
        cd EduCoder
        git config --global user.name "EduCoder Bot"
        git config --global user.email "bot@educoder.com"
        git add .
        git commit -m "Deploying to EduCoder"
        git push https://${EduCoder_USER}:${EduCoder_PASS}@${EduCoder_REPO}.git
