name: Integration testing
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison libfl-dev
          sudo apt-get install -y fpc
      - name: watch flex&bison
        run: |
          flex --version
          bison --version
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug --target kpc

      - name: Run Integration Tests
        run: |
          pwd
          ls -al
          mkdir res
          python3 tests/black-box/run-gencode.py tests/black-box/generate/ res
      # 检查res/failed/log/ 文件夹下是否有文件
      # 若存在，则输出文件夹中的所有文件及其内容，并 fail
      # 否则输出成功信息
      - name: Check for failed logs
        run: |
          if [ -d "res/failed/log" ] && [ "$(ls -A res/failed/log)" ]; then
            echo "Failed logs found:"
            ls res/failed/log
            for file in res/failed/log/*; do
              echo
              echo "Contents of $file:"
              cat "$file"
            done
            exit 1
          else
            echo "No failed logs found."
          fi
