name: Linux x64 Compiler

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CMake Test"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison libfl-dev
      - name: Verify Dependencies
        run: |
          flex --version
          bison --version
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=OFF
      - name: Build
        run: |
          cmake --build build --config Release --target kpc
          chmod +x build/kpc
          mv build/kpc build/kpc-linux-amd64

      - name: Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kpc-linux-amd64
          path: build/kpc-linux-amd64
          if-no-files-found: error
          retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/*
          token: ${{ secrets.TRANSPASCAL_CI }}
          body: |
            Multi-platform build for ${{ github.ref_name }}
            Supported systems:
            - Windows x64/arm64
            - Linux x64/arm64
            - macOS x64/arm64

  deploy-to-educoder:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Deploy to EduCoder
        env:
          EduCoder_USER: ${{ secrets.EduCoder_USER }}
          EduCoder_PASS: ${{ secrets.EduCoder_PASS }}
          EduCoder_REPO: ${{ secrets.EduCoder_REPO }}
        run: |
          echo "Deploying to EduCoder"
          git clone https://${EduCoder_USER}:${EduCoder_PASS}@${EduCoder_REPO}.git EduCoder
          ls -a
          ls -a artifacts
          echo "Moving kpc-linux-amd64 to EduCoder directory"
          pwd
          mv artifacts/kpc-linux-amd64 EduCoder/bin/pascc
          cd EduCoder
          git config --global user.name "EduCoder Bot"
          git config --global user.email "bot@educoder.com"
          git add .
          git commit -m "Deploying pascc to EduCoder by Github Actions"
          git push https://${EduCoder_USER}:${EduCoder_PASS}@${EduCoder_REPO}.git
          echo "Deployment to EduCoder completed"
