name: Mac x64 Compiler

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CMake Test"]
    types:
      - completed
jobs:
  build:
    runs-on: macos-latest  # macOS 运行器默认支持 x86_64 交叉编译

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew update
          brew install bison
          echo "PATH=$(brew --prefix bison)/bin:$PATH" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -DENABLE_TESTS=OFF

      - name: Build
        run: |
          cmake --build build --config Release --target kpc
          chmod +x build/kpc
          mv build/kpc build/kpc-macos-x86_64

      - name: Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kpc-macos-x86_64
          path: build/kpc-macos-x86_64
  create-release:
    needs: build
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/*
          token: ${{ secrets.TRANSPASCAL_CI }}
          body: |
            Multi-platform build for ${{ github.ref_name }}
            Supported systems:
            - Windows x64/arm64
            - Linux x64/arm64
            - MacOS arm64
