on:
    workflow_dispatch:
# TODO: 在 github 上没能正确运行， 配置有问题
jobs:
    post-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install clang-format clang-tidy cppcheck
                sudo pip install pre-commit
                pre-commit install
            - name: generate compile_commands.json
              run: |
                mkdir -p build
                cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build .
            - name: Run pre-commit hooks in post-commit
              run: |
                pre-commit run --all-files
