name: Windows x64 Build

on:
  # push:
  #   tags:
  #     - 'v*'
  #   branches: [ main ]
  # TODO:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # 将自带的MinGW更新到Latest
      - name: Update MinGW to Latest
        run: |
          # 通过Chocolatey安装最新版MinGW
          choco install mingw -y --force
          # 将MinGW添加到系统PATH
          $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          echo "Adding MinGW to PATH: $mingwPath"
          echo "$mingwPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

      # 安装win-flex-bison
      - name: Setup win-flex-bison
        run: |
          $url = "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          Invoke-WebRequest -Uri $url -OutFile win_flex_bison.zip
          Expand-Archive -Path win_flex_bison.zip -DestinationPath D:\win_flex_bison
          echo "D:\win_flex_bison" >> $env:GITHUB_PATH
          # 输出D:/win_flex_bison/下的所有路径
          Get-ChildItem -Path D:\win_flex_bison

      # 验证工具链
      - name: Verify Dependencies
        run: |
          win_flex --version
          win_bison --version
          cmake --version
          gcc --version
          g++ --version

      - name: Configure CMake
        run: |
          cmake -B build `
            -G "MinGW Makefiles" `
            -DCMAKE_BUILD_TYPE=Release `
            -DFLEX_EXECUTABLE=D:/win_flex_bison/win_flex.exe `
            -DBISON_EXECUTABLE=D:/win_flex_bison/win_bison.exe `
            -DCMAKE_CXX_FLAGS="-ID:/win_flex_bison"

      # 编译阶段
      - name: Build
        run: |
          cmake --build build --config Release --target kpc
          # rename kpc.exe to kpc-win-amd64.exe
          Rename-Item -Path build/kpc.exe -NewName build/kpc-win-amd64.exe

      # 产物打包
      - name: Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kpc-windows-x64
          path: build/kpc-win-amd64.exe
  create-release:
    needs: build
    runs-on: windows-latest
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/*
          token: ${{ secrets.TRANSPASCAL_CI }}
          body: |
            Multi-platform build for ${{ github.ref_name }}
            Supported systems:
            - Windows x64/arm64
            - Linux x64/arm64
            - MacOS arm64
